# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/mygit/NocProject/hw/Vivado/project_noc.cache/wt [current_project]
set_property parent.project_path D:/mygit/NocProject/hw/Vivado/project_noc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.7 [current_project]
set_property ip_repo_paths d:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet D:/mygit/NocProject/hw/Vivado/project_noc.runs/myFifo_synth_1/myFifo.dcp
set_property used_in_implementation false [get_files D:/mygit/NocProject/hw/Vivado/project_noc.runs/myFifo_synth_1/myFifo.dcp]
read_verilog -library xil_defaultlib {
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_scheduler.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_pe.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_switch.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_pe_2.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_block.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_block_2.v}
  {D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/imports/NOC project/nbyn_full.v}
}
read_xdc D:/mygit/NocProject/hw/Vivado/project_noc.srcs/constrs_1/new/noc.xdc
set_property used_in_implementation false [get_files D:/mygit/NocProject/hw/Vivado/project_noc.srcs/constrs_1/new/noc.xdc]

synth_design -top nbyn_full -part xc7vx690tffg1761-2
write_checkpoint -noxdef nbyn_full.dcp
catch { report_utilization -file nbyn_full_utilization_synth.rpt -pb nbyn_full_utilization_synth.pb }
