# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo.xci
# IP: The module: 'myFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myFifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo/myFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'myFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo.xci
# IP: The module: 'myFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/mygit/NocProject/hw/Vivado/project_noc.srcs/sources_1/ip/myFifo/myFifo/myFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'myFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
